"""
EXP-0002 figures.

Every figure answers one specific question (infrastructure/reporting.md). Figures are
generated by this committed script and are never hand-edited; each gets a sidecar
JSON recording the experiment, results file, script and commit that produced it.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt                                  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, ROOT)

RES = os.path.join(ROOT, "results", "validation", "EXP-0002")
FIG = os.path.join(ROOT, "results", "figures")

# Colour-vision-safe, readable in greyscale by ordering
COL = {"FC-1": "#1b6ca8", "FC-2": "#e07b39", "FC-3": "#2e8b57",
       "FC-4": "#b0b0b0", "FC-5": "#8b3a8b"}


def commit():
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT,
                                       text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:                                            # pragma: no cover
        return "unknown"


def sidecar(name, question, res):
    with open(os.path.join(FIG, f"{name}.json"), "w", encoding="utf-8") as fh:
        json.dump({
            "figure": name,
            "question_answered": question,
            "experiment_id": "EXP-0002",
            "results_file": "results/validation/EXP-0002/exp0002_results.json",
            "dataset_ids": ["DS-0001"],
            "script": "visualization/plot_exp0002.py",
            "git_commit": commit(),
            "generated_from_results_utc": res["generated_utc"],
        }, fh, indent=2)


def main():
    os.makedirs(FIG, exist_ok=True)
    with open(os.path.join(RES, "exp0002_results.json"), "r", encoding="utf-8") as fh:
        res = json.load(fh)

    ids = res["fault_ids"]
    valid = res["valid_conditions"]
    invalid = res["invalid_conditions"]
    tau = res["threshold_primary"]

    D = {}
    for fc in valid + invalid:
        M = np.loadtxt(os.path.join(RES, f"distance_matrix_{fc}.csv"),
                       delimiter=",", skiprows=1)
        D[fc] = M
    iu = np.triu_indices(len(ids), k=1)

    # ---------------------------------------------------------------- FIG-001
    # Q: does the amount of fault ambiguity depend on flight condition?
    fig, ax = plt.subplots(1, 2, figsize=(12, 4.6))

    taus = [float(t) for t in res["threshold_sweep"].keys()]
    for fc in valid:
        n = [res["threshold_sweep"][str(t)][fc]["n_distinguishable"] for t in taus]
        ax[0].plot(taus, n, "o-", color=COL[fc], label=f"{fc} (valid)", lw=2)
    for fc in invalid:
        n = [res["threshold_sweep"][str(t)][fc]["n_distinguishable"] for t in taus]
        ax[0].plot(taus, n, "s--", color=COL[fc], label=f"{fc} (INVALID, FAIL-0001)",
                   lw=1.4, alpha=0.85)
    ax[0].axvline(tau, color="k", ls=":", lw=1)
    ax[0].annotate(f"primary\n$\\tau$={tau:g}", (tau, 8), fontsize=8, ha="center")
    ax[0].set_xscale("log")
    ax[0].set_xlabel(r"threshold $\tau$  (multiples of RMS sensor noise)")
    ax[0].set_ylabel("distinguishable pairs (of 153)")
    ax[0].set_title("Ambiguity vs threshold, per flight condition")
    ax[0].legend(fontsize=7.5, loc="upper right")
    ax[0].grid(alpha=0.3)

    order = valid + invalid
    box = [D[fc][iu] for fc in order]
    bp = ax[1].boxplot(box, showfliers=False, patch_artist=True,
                     tick_labels=order)
    for patch, fc in zip(bp["boxes"], order):
        patch.set_facecolor(COL[fc])
        patch.set_alpha(0.55)
    ax[1].axhline(tau, color="k", ls=":", lw=1, label=rf"$\tau$={tau:g}")
    ax[1].set_yscale("log")
    ax[1].set_ylabel(r"pairwise distance $d_{ij}$  (RMS noise units)")
    ax[1].set_title("Distance distribution per condition")
    ax[1].legend(fontsize=8)
    ax[1].grid(alpha=0.3, axis="y")
    for i, fc in enumerate(order):
        if fc in invalid:
            ax[1].text(i + 1, ax[1].get_ylim()[1] * 0.55, "INVALID",
                       ha="center", fontsize=7, color="#7a0000", rotation=90)

    fig.suptitle("EXP-0002  Response-based fault distinguishability "
                 "(GFW-1, deterministic, noise-free)", fontsize=11)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "FIG-001-distinguishability-vs-condition.png"), dpi=150)
    plt.close(fig)
    sidecar("FIG-001-distinguishability-vs-condition",
            "Does the amount of fault ambiguity depend on flight condition?", res)

    # ---------------------------------------------------------------- FIG-002
    # Q: which faults form the ambiguity group, and does it change with condition?
    n = len(ids)
    fig, axes = plt.subplots(1, len(valid), figsize=(4.4 * len(valid), 4.8))
    if len(valid) == 1:
        axes = [axes]
    for ax_, fc in zip(axes, valid):
        B = (D[fc] <= tau).astype(float)
        np.fill_diagonal(B, 0.5)
        ax_.imshow(B, cmap="Greys", vmin=0, vmax=1, interpolation="nearest")
        ax_.set_xticks(range(n))
        ax_.set_yticks(range(n))
        ax_.set_xticklabels(ids, rotation=90, fontsize=6)
        ax_.set_yticklabels(ids, fontsize=6)
        na = int(B[np.triu_indices(n, 1)].sum())
        ax_.set_title(f"{fc}  ({na} indistinguishable pairs)", fontsize=9)
        ax_.set_xticks(np.arange(-.5, n, 1), minor=True)
        ax_.set_yticks(np.arange(-.5, n, 1), minor=True)
        ax_.grid(which="minor", color="w", lw=0.5)
    fig.suptitle(f"Indistinguishable fault pairs (black) at $\\tau$={tau:g} — valid conditions only",
                 fontsize=11)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "FIG-002-ambiguity-matrices.png"), dpi=150)
    plt.close(fig)
    sidecar("FIG-002-ambiguity-matrices",
            "Which fault pairs are indistinguishable, and does the set change with condition?",
            res)

    # ---------------------------------------------------------------- FIG-003
    # Q: is the bias/scale confusion on a regulated channel predictable in closed form?
    fig, ax = plt.subplots(figsize=(6.6, 4.4))
    trim = res["trim"]
    pts = []
    i1, i2 = ids.index("F1_Vt"), ids.index("F2_Vt")
    for fc in valid:
        V0 = trim[fc]["Vt"]
        pts.append((V0, D[fc][i1, i2], fc))
    pts.sort()
    ax.plot([p[0] for p in pts], [p[1] for p in pts], "o-", color="#1b6ca8", lw=2,
            label=r"measured $d$(F1_Vt, F2_Vt)")
    for V0, d, fc in pts:
        ax.annotate(f"  {fc}", (V0, d), fontsize=8, va="center")
    Vg = np.linspace(20, 52, 200)
    b, k = 10 * 0.5, 1.10
    ax.plot(Vg, np.abs(b - (k - 1) * Vg) / 0.5 / np.sqrt(13), "--", color="#b03060",
            label=r"analytic: $|b-(k{-}1)V_0|/\sigma_{V}$, diluted over 13 channels")
    ax.axvline(b / (k - 1), color="k", ls=":", lw=1)
    ax.annotate(r"$V^*=b/(k{-}1)$" + f"\n= {b/(k-1):.0f} m/s", (b / (k - 1), ax.get_ylim()[1] * 0.6),
                fontsize=8, ha="right")
    ax.axhline(tau, color="grey", ls="-.", lw=1, label=rf"$\tau$={tau:g}")
    ax.set_xlabel("trim airspeed $V_0$  (m/s)")
    ax.set_ylabel(r"$d$  (RMS noise units)")
    ax.set_title("A bias fault and a scale fault on a regulated channel\n"
                 "become indistinguishable at a predictable airspeed", fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "FIG-003-bias-scale-crossover.png"), dpi=150)
    plt.close(fig)
    sidecar("FIG-003-bias-scale-crossover",
            "Is the condition-dependent bias/scale ambiguity predictable in closed form?", res)

    print("wrote FIG-001, FIG-002, FIG-003 to results/figures/")


if __name__ == "__main__":
    raise SystemExit(main())
